[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r sentiment-sphere/api/requirements.txt"

[deploy]
startCommand = "cd sentiment-sphere/api && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"

[[services]]
name = "sentimizer-api"
